### ISSUE TITLE
Exception during export while "Locating all textures"

### ISSUE THREAD

**Issue by mediadog** [acgessler/open3mod#52]
Tried exporting as .dae and .obj, turned on and off "Copy textures..." and "Use realtive texture paths" etc., same result.  Exceptio happens after first two textures processed.  Version 1.1 on Win7 x64 GTX970.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at open3mod.TextureLoader.ObtainStream(String name, String basedir, String& actualLocation)
   at open3mod.ExportDialog.DoExport(Scene scene, String id)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by thebravyone** [comment]
:thumbsup:

**Comment by thebravyone** [comment]
having the same issue here
